[[templates.mandelbrot]]
fractal = "mandelbrot"
center_x = -0.5
center_y = 0.0
zoom = 1.0
max_iter = 255

[[templates.spirals]]
fractal = "mandelbrot"
center_x = -0.7345
center_y = 0.181
zoom = 250
max_iter = 255
